### ISSUE TITLE
Operation bloc not reset

### ISSUE THREAD

**Issue by vephisto** [wll8/redoc-try#28]
Hi!

When I click on "Try" button on my endpoint A, the operation block is displayed and I can test the endpoint that returns a response.
Then I don't close the block and when I click on the "Try" button, on my endpoint B, it displays the operation block but the content is the result of my previous test on endpoint A and block is not well sized.
To restore the block I have to close the block and reopen it with "Try" button.

Another thing I've noticed, is that my operations blocks aren't displayed on the right like in your demo (links on your Readme), but in the main part instead. It's not a problem, but I'd rather tell you about it in case it is related.

Thx!

**Comment by wll8** [comment]
If you are willing to provide a link where the problem can be reproduced, I will fix it soon.

**Comment by vephisto** [comment]
I can but not publicly. Could you provide me an email to send it to you please?

**Comment by wll8** [comment]
Can you try a minimal reproducible example with sensitive information removed?

``` html
<body>
  <div id="redoc-container"></div>
  <script src="https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.55/bundles/redoc.standalone.min.js"> </script>
  <script src="https://cdn.jsdelivr.net/gh/wll8/redoc-try@1.4.3/dist/try.js"></script>
  <script>
    initTry({
      openApi: {}, // Put your openApi json data here, pay attention to remove sensitive content
    })
  </script>
</body>
```

Click to see an example: https://codepen.io/wll8/pen/jOQYxOE

**Comment by vephisto** [comment]
You'll find an example below.
I noticed that I am using redoc@2.0.0 but you are using redoc@2.0.0-rc55, but I can reproduce with both.

Other thing I noticed is that I only have the bug when the endpoint returns a result. If I use a fake API url or if I am not authenticated I don't have the bug. So with this example you will not reproduce until you provide a functional API url and the required authorization.
And sometimes I need to click multiple times on the "Try" button to have the bug. It sounds like the operation block is the same for each endpoint but is not always refreshed.


```
<body>
  <div id="redoc-container"></div>
  <script src="https://cdn.jsdelivr.net/npm/redoc@2.0.0/bundles/redoc.standalone.min.js"> </script>
  <script src="https://cdn.jsdelivr.net/gh/wll8/redoc-try@1.4.3/dist/try.js"></script>
  <script>
    initTry({
      "openApi": {
	   "openapi": "3.0.3",
	   "info": {
	      "version": "2.0.0",
	      "title": "Test API",
	      "description": "# Introduction\nOK"
	   },
	   "servers": [
	      {
		 "url": "https://mytestapi.com"
	      }
	   ],
	   "security": [
	      {
		 "ApiKey": []
	      }
	   ],
	   "tags": [
	      {
		 "name": "Endpoints"
	      },
	      {
		 "name": "Narration",
		 "description": "Narration description."
	      },
	      {
		 "name": "Usage",
		 "description": "Get informations about API usage."
	      }
	   ],
	   "paths": {
	      "/narration": {
		 "post": {
		    "tags": [
		       "Narration"
		    ],
		    "summary": "Create narration\n",
		    "description": "Narration description\n",
		    "operationId": "postNarration",
		    "requestBody": {
		       "description": "Create a new narration",
		       "content": {
		          "application/json": {
		             "schema": {
		                "type": "object",
		                "required": [
		                   "format",
		                   "items",
		                   "items.type"
		                ],
		                "properties": {
		                   "format": {
		                      "description": "Desired output format",
		                      "type": "string",
		                      "enum": [
		                         "audio_mp3_low",
		                         "audio_mp3_standard",
		                         "audio_mp3_high",
		                         "audio_wav"
		                      ]
		                   },
		                   "items": {
		                      "description": "Audio files and texts to be rendered",
		                      "type": "array",
		                      "items": {
		                         "anyOf": [
		                            {
		                               "type": "object",
		                               "title": "ItemText",
		                               "required": [
		                                  "type",
		                                  "text",
		                                  "voiceId"
		                               ],
		                               "properties": {
		                                  "type": {
		                                     "description": "Text item",
		                                     "type": "string",
		                                     "enum": [
		                                        "text"
		                                     ]
		                                  },
		                                  "text": {
		                                     "description": "Text to add to narration",
		                                     "type": "string"
		                                  },
		                                  "voiceId": {
		                                     "description": "Voice identifier to apply to item",
		                                     "type": "string"
		                                  }
		                               }
		                            },
		                            {
		                               "type": "object",
		                               "title": "ItemAudio",
		                               "required": [
		                                  "type",
		                                  "audio"
		                               ],
		                               "properties": {
		                                  "type": {
		                                     "description": "Audio item",
		                                     "type": "string",
		                                     "enum": [
		                                        "audio"
		                                     ]
		                                  },
		                                  "audio": {
		                                     "description": "Audio file URL to add to narration",
		                                     "type": "string"
		                                  }
		                               }
		                            }
		                         ]
		                      }
		                   },
		                   "callbackUrl": {
		                      "description": "Test description.\n",
		                      "type": "string",
		                      "format": "url"
		                   }
		                }
		             }
		          }
		       }
		    },
		    "responses": {
		       "200": {
		          "description": "Success",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "type": "object",
		                   "properties": {
		                      "id": {
		                         "type": "string",
		                         "description": "The id of the narration"
		                      },
		                      "receivedAt": {
		                         "type": "string",
		                         "format": "datetime",
		                         "description": "The date (UTC) on which the narration has been taken into account"
		                      }
		                   }
		                }
		             }
		          }
		       },
		       "403": {
		          "description": "Forbidden",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "$ref": "#/components/schemas/ApiErrorForbidden"
		                }
		             }
		          }
		       },
		       "4xx": {
		          "description": "Bad request / Unauthorized",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "$ref": "#/components/schemas/ApiErrorGlobal"
		                }
		             }
		          }
		       },
		       "5xx": {
		          "description": "Internal server error / Service unavailable",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "$ref": "#/components/schemas/ApiErrorGlobal"
		                }
		             }
		          }
		       }
		    }
		 }
	      },
	      "/narration/{narrationId}": {
		 "get": {
		    "tags": [
		       "Narration"
		    ],
		    "summary": "Get narration",
		    "description": "Get narration according to the narration id\n(see [Post narration](#tag/Narration/operation/postNarration) endpoint).\n",
		    "operationId": "getNarration",
		    "parameters": [
		       {
		          "in": "path",
		          "name": "narrationId",
		          "schema": {
		             "type": "string"
		          },
		          "description": "The id of the narration"
		       }
		    ],
		    "responses": {
		       "200": {
		          "description": "Success",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "type": "object",
		                   "properties": {
		                      "id": {
		                         "type": "string",
		                         "description": "Id of the narration"
		                      },
		                      "status": {
		                         "type": "string",
		                         "description": "Status of the audio generation",
		                         "enum": [
		                            "waiting",
		                            "rendering",
		                            "success",
		                            "failed"
		                         ]
		                      },
		                      "error": {
		                         "type": "object",
		                         "description": "Not null only if status is `failed`",
		                         "properties": {
		                            "code": {
		                               "type": "string",
		                               "description": "Error code"
		                            },
		                            "message": {
		                               "type": "string",
		                               "description": "Error message"
		                            }
		                         }
		                      },
		                      "createdAt": {
		                         "type": "string",
		                         "format": "datetime",
		                         "description": "Creation date (UTC) of the narration"
		                      },
		                      "renderStartedAt": {
		                         "type": "string",
		                         "format": "datetime",
		                         "description": "Start date (UTC) of the audio rendering treatment"
		                      },
		                      "renderEndedt": {
		                         "type": "string",
		                         "format": "datetime",
		                         "description": "End date (UTC) of the audio rendering treatment; only in case of success"
		                      },
		                      "output": {
		                         "type": "string",
		                         "format": "url",
		                         "description": "URL of the audio generation"
		                      },
		                      "creditsUsed": {
		                         "type": "integer",
		                         "description": "Number of characters counted for narration"
		                      },
		                      "creditsRemaining": {
		                         "type": "integer",
		                         "description": "Number of remaining characters according to the quota\n(see [Get usage](#tag/Narration/operation/getUsage) endpoint)\n"
		                      },
		                      "duration": {
		                         "type": "integer",
		                         "description": "Duration of generated audio"
		                      }
		                   }
		                }
		             }
		          }
		       },
		       "401": {
		          "description": "Unauthorized",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "$ref": "#/components/schemas/ApiErrorGlobal"
		                }
		             }
		          }
		       },
		       "403": {
		          "description": "Forbidden",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "$ref": "#/components/schemas/ApiErrorForbidden"
		                }
		             }
		          }
		       },
		       "5xx": {
		          "description": "Internal server error / Service unavailable",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "$ref": "#/components/schemas/ApiErrorGlobal"
		                }
		             }
		          }
		       }
		    }
		 }
	      },
	      "/usage": {
		 "get": {
		    "tags": [
		       "Usage"
		    ],
		    "summary": "Get API usage\n",
		    "description": "Get API usage for current month.\n",
		    "operationId": "getUsage",
		    "responses": {
		       "200": {
		          "description": "Success",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "type": "object",
		                   "properties": {
		                      "startDate": {
		                         "type": "string",
		                         "format": "datetime",
		                         "description": "Start date (UTC) of the current month subscription (first day of the month)"
		                      },
		                      "endDate": {
		                         "type": "string",
		                         "format": "datetime",
		                         "description": "End date (UTC) of the current month subscription (last day of the month)"
		                      },
		                      "quota": {
		                         "type": "integer",
		                         "description": "Subscribed quota"
		                      },
		                      "creditsUsed": {
		                         "type": "integer",
		                         "description": "Number of characters used for current month"
		                      },
		                      "creditsUsedPercentage": {
		                         "type": "number",
		                         "description": "Percentage of characters used, compared to quota, for current month"
		                      },
		                      "creditsRemaining": {
		                         "type": "integer",
		                         "description": "Number of remaining characters for current month"
		                      }
		                   }
		                }
		             }
		          }
		       },
		       "403": {
		          "description": "Forbidden",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "$ref": "#/components/schemas/ApiErrorForbidden"
		                }
		             }
		          }
		       },
		       "4xx": {
		          "description": "Bad request / Not found / Payload too large / Unauthorized",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "$ref": "#/components/schemas/ApiErrorGlobal"
		                }
		             }
		          }
		       },
		       "5xx": {
		          "description": "Internal server error / Service unavailable",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "$ref": "#/components/schemas/ApiErrorGlobal"
		                }
		             }
		          }
		       }
		    }
		 }
	      }
	   },
	   "components": {
	      "securitySchemes": {
		 "ApiKey": {
		    "type": "apiKey",
		    "in": "header",
		    "name": "x-api-key",
		    "description": "Test description."
		 }
	      },
	      "schemas": {
		 "ApiErrorGlobal": {
		    "type": "object",
		    "properties": {
		       "errorCode": {
		          "type": "string",
		          "description": "The error code"
		       },
		       "message": {
		          "type": "string",
		          "description": "The error message"
		       }
		    }
		 },
		 "ApiErrorForbidden": {
		    "type": "object",
		    "properties": {
		       "message": {
		          "type": "string",
		          "description": "The error message"
		       }
		    }
		 }
	      }
	   },
	   "x-tagGroups": [
	      {
		 "name": "Endpoints",
		 "tags": [
		    "Narration",
		    "Usage"
		 ]
	      }
	   ]
	}
    })
  </script>
</body>
```

**Comment by vephisto** [comment]
You'll find a little, and dirty (sorry), video capture as attachement

https://github.com/wll8/redoc-try/assets/127130272/f6bc097e-c30e-43e6-ac2c-13908fad1770

**Comment by wll8** [comment]
It looks like I reproduced the error using the code you provided.

I expected to start working on this issue two days later.

![image](https://github.com/wll8/redoc-try/assets/28223260/57ef021e-e08c-45ea-929b-8d162ef8b99c)

**Comment by wll8** [comment]
When I use `redoc@2.0.0-rc55`, the phenomenon in my screenshot above does not reappear.

![image](https://github.com/wll8/redoc-try/assets/28223260/4e8400fb-bdf6-41f6-b305-02320c2925f8)

Due to the `redoc@2.0.0` version, there will be two layers of data-section-id, resulting in a logic error.

The solution is as follows:
![image](https://github.com/wll8/redoc-try/assets/28223260/03d3fe75-08a5-45c3-b968-5f54a092909f)

Now you can try version [redoc-try@1.4.4](https://github.com/wll8/redoc-try/compare/1.4.3...1.4.4) to verify that the problem is fixed.

**Comment by vephisto** [comment]
Sorry for my late answer, I was out of office.
With this new version I have now the operation bloc on the right but I still have some displaying problems.

1. I click on "try" button on 1st endpoint and execute the request
2. I click on "try" button on 2nd endpoint:
- sometimes it does not display the operation bloc but it closes the operation bloc at the 1st endpoint level, so I have to click on it again to display it at the 2nd endpoint level
- sometimes it displays the result of the operation bloc of the 1st endpoint in the operation bloc of 2nd endpoint (see attachment)
![Screenshot from 2023-07-19 10-56-55](https://github.com/wll8/redoc-try/assets/127130272/32fa5f79-f416-4698-ab41-bbe00354a648)

**Comment by wll8** [comment]
It happens "sometimes", not always, right? Because I did not find such a similar phenomenon that api1 is displayed in the position of api2. Here is the code I use:

<details>

``` html

<body>
  <div id="redoc-container"></div>
  <script src="https://cdn.jsdelivr.net/npm/redoc@2.0.0/bundles/redoc.standalone.min.js"> </script>
  <script src="https://cdn.jsdelivr.net/gh/wll8/redoc-try@1.4.4/dist/try.js"></script>
  <script>
    initTry({
      "openApi": {
	   "openapi": "3.0.3",
	   "info": {
	      "version": "2.0.0",
	      "title": "Test API",
	      "description": "# Introduction\nOK"
	   },
	   "servers": [
	      {
		 "url": "https://httpbin.org/anything"
	      }
	   ],
	   "security": [
	      {
		 "ApiKey": []
	      }
	   ],
	   "tags": [
	      {
		 "name": "Endpoints"
	      },
	      {
		 "name": "Narration",
		 "description": "Narration description."
	      },
	      {
		 "name": "Usage",
		 "description": "Get informations about API usage."
	      }
	   ],
	   "paths": {
	      "/narration": {
		 "post": {
		    "tags": [
		       "Narration"
		    ],
		    "summary": "Create narration\n",
		    "description": "Narration description\n",
		    "operationId": "postNarration",
		    "requestBody": {
		       "description": "Create a new narration",
		       "content": {
		          "application/json": {
		             "schema": {
		                "type": "object",
		                "required": [
		                   "format",
		                   "items",
		                   "items.type"
		                ],
		                "properties": {
		                   "format": {
		                      "description": "Desired output format",
		                      "type": "string",
		                      "enum": [
		                         "audio_mp3_low",
		                         "audio_mp3_standard",
		                         "audio_mp3_high",
		                         "audio_wav"
		                      ]
		                   },
		                   "items": {
		                      "description": "Audio files and texts to be rendered",
		                      "type": "array",
		                      "items": {
		                         "anyOf": [
		                            {
		                               "type": "object",
		                               "title": "ItemText",
		                               "required": [
		                                  "type",
		                                  "text",
		                                  "voiceId"
		                               ],
		                               "properties": {
		                                  "type": {
		                                     "description": "Text item",
		                                     "type": "string",
		                                     "enum": [
		                                        "text"
		                                     ]
		                                  },
		                                  "text": {
		                                     "description": "Text to add to narration",
		                                     "type": "string"
		                                  },
		                                  "voiceId": {
		                                     "description": "Voice identifier to apply to item",
		                                     "type": "string"
		                                  }
		                               }
		                            },
		                            {
		                               "type": "object",
		                               "title": "ItemAudio",
		                               "required": [
		                                  "type",
		                                  "audio"
		                               ],
		                               "properties": {
		                                  "type": {
		                                     "description": "Audio item",
		                                     "type": "string",
		                                     "enum": [
		                                        "audio"
		                                     ]
		                                  },
		                                  "audio": {
		                                     "description": "Audio file URL to add to narration",
		                                     "type": "string"
		                                  }
		                               }
		                            }
		                         ]
		                      }
		                   },
		                   "callbackUrl": {
		                      "description": "Test description.\n",
		                      "type": "string",
		                      "format": "url"
		                   }
		                }
		             }
		          }
		       }
		    },
		    "responses": {
		       "200": {
		          "description": "Success",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "type": "object",
		                   "properties": {
		                      "id": {
		                         "type": "string",
		                         "description": "The id of the narration"
		                      },
		                      "receivedAt": {
		                         "type": "string",
		                         "format": "datetime",
		                         "description": "The date (UTC) on which the narration has been taken into account"
		                      }
		                   }
		                }
		             }
		          }
		       },
		       "403": {
		          "description": "Forbidden",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "$ref": "#/components/schemas/ApiErrorForbidden"
		                }
		             }
		          }
		       },
		       "4xx": {
		          "description": "Bad request / Unauthorized",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "$ref": "#/components/schemas/ApiErrorGlobal"
		                }
		             }
		          }
		       },
		       "5xx": {
		          "description": "Internal server error / Service unavailable",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "$ref": "#/components/schemas/ApiErrorGlobal"
		                }
		             }
		          }
		       }
		    }
		 }
	      },
	      "/narration/{narrationId}": {
		 "get": {
		    "tags": [
		       "Narration"
		    ],
		    "summary": "Get narration",
		    "description": "Get narration according to the narration id\n(see [Post narration](#tag/Narration/operation/postNarration) endpoint).\n",
		    "operationId": "getNarration",
		    "parameters": [
		       {
		          "in": "path",
		          "name": "narrationId",
		          "schema": {
		             "type": "string"
		          },
		          "description": "The id of the narration"
		       }
		    ],
		    "responses": {
		       "200": {
		          "description": "Success",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "type": "object",
		                   "properties": {
		                      "id": {
		                         "type": "string",
		                         "description": "Id of the narration"
		                      },
		                      "status": {
		                         "type": "string",
		                         "description": "Status of the audio generation",
		                         "enum": [
		                            "waiting",
		                            "rendering",
		                            "success",
		                            "failed"
		                         ]
		                      },
		                      "error": {
		                         "type": "object",
		                         "description": "Not null only if status is `failed`",
		                         "properties": {
		                            "code": {
		                               "type": "string",
		                               "description": "Error code"
		                            },
		                            "message": {
		                               "type": "string",
		                               "description": "Error message"
		                            }
		                         }
		                      },
		                      "createdAt": {
		                         "type": "string",
		                         "format": "datetime",
		                         "description": "Creation date (UTC) of the narration"
		                      },
		                      "renderStartedAt": {
		                         "type": "string",
		                         "format": "datetime",
		                         "description": "Start date (UTC) of the audio rendering treatment"
		                      },
		                      "renderEndedt": {
		                         "type": "string",
		                         "format": "datetime",
		                         "description": "End date (UTC) of the audio rendering treatment; only in case of success"
		                      },
		                      "output": {
		                         "type": "string",
		                         "format": "url",
		                         "description": "URL of the audio generation"
		                      },
		                      "creditsUsed": {
		                         "type": "integer",
		                         "description": "Number of characters counted for narration"
		                      },
		                      "creditsRemaining": {
		                         "type": "integer",
		                         "description": "Number of remaining characters according to the quota\n(see [Get usage](#tag/Narration/operation/getUsage) endpoint)\n"
		                      },
		                      "duration": {
		                         "type": "integer",
		                         "description": "Duration of generated audio"
		                      }
		                   }
		                }
		             }
		          }
		       },
		       "401": {
		          "description": "Unauthorized",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "$ref": "#/components/schemas/ApiErrorGlobal"
		                }
		             }
		          }
		       },
		       "403": {
		          "description": "Forbidden",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "$ref": "#/components/schemas/ApiErrorForbidden"
		                }
		             }
		          }
		       },
		       "5xx": {
		          "description": "Internal server error / Service unavailable",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "$ref": "#/components/schemas/ApiErrorGlobal"
		                }
		             }
		          }
		       }
		    }
		 }
	      },
	      "/usage": {
		 "get": {
		    "tags": [
		       "Usage"
		    ],
		    "summary": "Get API usage\n",
		    "description": "Get API usage for current month.\n",
		    "operationId": "getUsage",
		    "responses": {
		       "200": {
		          "description": "Success",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "type": "object",
		                   "properties": {
		                      "startDate": {
		                         "type": "string",
		                         "format": "datetime",
		                         "description": "Start date (UTC) of the current month subscription (first day of the month)"
		                      },
		                      "endDate": {
		                         "type": "string",
		                         "format": "datetime",
		                         "description": "End date (UTC) of the current month subscription (last day of the month)"
		                      },
		                      "quota": {
		                         "type": "integer",
		                         "description": "Subscribed quota"
		                      },
		                      "creditsUsed": {
		                         "type": "integer",
		                         "description": "Number of characters used for current month"
		                      },
		                      "creditsUsedPercentage": {
		                         "type": "number",
		                         "description": "Percentage of characters used, compared to quota, for current month"
		                      },
		                      "creditsRemaining": {
		                         "type": "integer",
		                         "description": "Number of remaining characters for current month"
		                      }
		                   }
		                }
		             }
		          }
		       },
		       "403": {
		          "description": "Forbidden",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "$ref": "#/components/schemas/ApiErrorForbidden"
		                }
		             }
		          }
		       },
		       "4xx": {
		          "description": "Bad request / Not found / Payload too large / Unauthorized",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "$ref": "#/components/schemas/ApiErrorGlobal"
		                }
		             }
		          }
		       },
		       "5xx": {
		          "description": "Internal server error / Service unavailable",
		          "content": {
		             "application/json": {
		                "schema": {
		                   "$ref": "#/components/schemas/ApiErrorGlobal"
		                }
		             }
		          }
		       }
		    }
		 }
	      }
	   },
	   "components": {
	      "securitySchemes": {
		 "ApiKey": {
		    "type": "apiKey",
		    "in": "header",
		    "name": "x-api-key",
		    "description": "Test description."
		 }
	      },
	      "schemas": {
		 "ApiErrorGlobal": {
		    "type": "object",
		    "properties": {
		       "errorCode": {
		          "type": "string",
		          "description": "The error code"
		       },
		       "message": {
		          "type": "string",
		          "description": "The error message"
		       }
		    }
		 },
		 "ApiErrorForbidden": {
		    "type": "object",
		    "properties": {
		       "message": {
		          "type": "string",
		          "description": "The error message"
		       }
		    }
		 }
	      }
	   },
	   "x-tagGroups": [
	      {
		 "name": "Endpoints",
		 "tags": [
		    "Narration",
		    "Usage"
		 ]
	      }
	   ]
	}
    })
  </script>
</body>

```
</details>

**Comment by vephisto** [comment]
Indeed with your code I don't have the problem...
So I tried to start from your code and added my features step by step and it seems that the problem occurs when I set the yaml file in openApi attribute instead of json object. 
```
<script>
      initTry({ openApi: "./openapi.yaml", tryText: "Try", redocOptions: { hideDownloadButton: true } });
    </script>
```

So I'm wondering if it's possible to use YAML... maybe I've been wrong all along?

**Comment by wll8** [comment]
Here's an example using yaml:

https://wll8.github.io/redoc-try/index.html?openApi=./test/openapi.3.yaml

Can you create a project that reproduces the problem? For example:

https://codesandbox.io/s/dreamy-curran-7j9p6j

It allows to log in directly with github.

**Comment by vephisto** [comment]
I can reproduce with this project : https://codesandbox.io/s/sleepy-banach-ghtk6p

Can you see the problem too?

**Comment by wll8** [comment]
Is this the problem you describe?

https://github.com/wll8/redoc-try/assets/28223260/5429c707-4058-40d6-8153-a898a17f3317

**Comment by wll8** [comment]
Now you can try version [redoc-try@1.4.7](https://github.com/wll8/redoc-try/compare/1.4.6...1.4.7) to verify that the problem is fixed.

https://codesandbox.io/s/redoc-try-issues-28-x6rpw7

**Comment by vephisto** [comment]
It works ! Thanks @wll8 for your time and your work!
